# Generated by Django 2.2.9 on 2020-01-29 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cm', '0046_auto_20200120_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='action',
            name='allow_to_terminate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stageaction',
            name='allow_to_terminate',
            field=models.BooleanField(default=False),
        ),
    ]
